# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TabMainPages.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from WebBlock import Ui_MainWindow1
from ReminderCustom import Ui_MainWindow2
from todolist import Ui_MainWindow3
import sys

class Ui_MainWindow(QtWidgets.QWidget):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/img/sunset.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 761))
        self.tabWidget.setObjectName("tabWidget")
        self.starting = QtWidgets.QWidget()
        self.starting.setObjectName("starting")
        self.tabWidget.addTab(self.starting, "")
        self.webblockerpage = QtWidgets.QWidget()
        self.webblockerpage.setObjectName("webblockerpage")
        self.tabWidget.addTab(self.webblockerpage, "")

        self.reminderpage = QtWidgets.QWidget()
        self.reminderpage.setObjectName("reminderpage")
        self.tabWidget.addTab(self.reminderpage, "")

        self.todolistpage = QtWidgets.QWidget()
        self.todolistpage.setObjectName("todolistpage")
        self.tabWidget.addTab(self.todolistpage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.starting), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.webblockerpage), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reminderpage), _translate("MainWindow", "Page"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.todolistpage), _translate("MainWindow", "Page"))
import Resource





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
