# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Testing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import time
from PyQt5.QtWidgets import QLabel


class Ui_MainWindow4(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/img/sunset.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 580, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"    color: white;\n"
"    border-style: outset;\n"
"    border-width: 4px;\n"
"    border-radius: 30px;\n"
"    border-color: beige;\n"
"    padding: 9px;\n"
"    \n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 130, 480, 105))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(39)
        self.label.setFont(font)

        self.label.setStyleSheet("\n"
                                        "QLabel {\n"
                                        "    color: white;\n"
                                        "    border-style: inset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 30px;\n"
                                        "    border-color: beige;\n"
                                        "    padding: 9px;\n"
                                        "    \n"
                                        "}")

        self.label.setText(QtCore.QDate.currentDate().toString())


        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 245, 480, 65))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(30)
        self.label_2.setFont(font)

        self.label_2.setStyleSheet("\n"
                                 "QLabel {\n"
                                 "    color: white;\n"
                                 "    border-style: inset;\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius: 30px;\n"
                                 "    border-color: beige;\n"
                                 "    padding: 9px;\n"
                                 "    \n"
                                 "}")

        self.label_2.setText(QtCore.QTime.currentTime().toString())


        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Begin Timer"))
import Resource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow4()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
