# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/img/sunset.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.AddToList = QtWidgets.QPushButton(self.centralwidget)
        self.AddToList.setGeometry(QtCore.QRect(210, 550, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.AddToList.setFont(font)
        self.AddToList.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.AddToList.setObjectName("AddToList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 110, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setAcceptDrops(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 0, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.backButton.setFont(font)
        self.backButton.setStyleSheet("color: beige;\n"
"border-style: groove;\n"
"border-width: 1px;\n"
"border-color:beige;\n"
"")
        self.backButton.setObjectName("backButton")
        self.DelFromList = QtWidgets.QPushButton(self.centralwidget)
        self.DelFromList.setGeometry(QtCore.QRect(500, 550, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.DelFromList.setFont(font)
        self.DelFromList.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.DelFromList.setObjectName("DelFromList")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(120, 200, 681, 301))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("border-radius:45px;\n"
"color:white;\n"
"padding: 20px;")
        self.listWidget.setObjectName("listWidget")
        self.EditButton = QtWidgets.QPushButton(self.centralwidget)
        self.EditButton.setGeometry(QtCore.QRect(210, 640, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EditButton.setFont(font)
        self.EditButton.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.EditButton.setObjectName("EditButton")
        self.SortButton = QtWidgets.QPushButton(self.centralwidget)
        self.SortButton.setGeometry(QtCore.QRect(500, 640, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SortButton.setFont(font)
        self.SortButton.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.SortButton.setObjectName("SortButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddToList.setText(_translate("MainWindow", "ADD TASK"))
        self.label.setText(_translate("MainWindow", "             .TO DO LIST."))
        self.backButton.setText(_translate("MainWindow", "back"))
        self.DelFromList.setText(_translate("MainWindow", "TASK COMPLETE"))
        self.EditButton.setText(_translate("MainWindow", "EDIT TASK"))
        self.SortButton.setText(_translate("MainWindow", "SORT OUT"))
import Resource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
