# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WebBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(932, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(:/img/sunset.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 290, 721, 61))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-radius:30px;\n"
"color:white;\n"
"padding:9px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.blockButton = QtWidgets.QPushButton(self.centralwidget)
        self.blockButton.setGeometry(QtCore.QRect(200, 400, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.blockButton.setFont(font)
        self.blockButton.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.blockButton.setObjectName("blockButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 200, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setAcceptDrops(False)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.backforwb = QtWidgets.QPushButton(self.centralwidget)
        self.backforwb.setGeometry(QtCore.QRect(0, 0, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.backforwb.setFont(font)
        self.backforwb.setStyleSheet("color: beige;\n"
"border-style: groove;\n"
"border-width: 1px;\n"
"border-color:beige;\n"
"")
        self.backforwb.setObjectName("backforwb")
        self.unblockButton = QtWidgets.QPushButton(self.centralwidget)
        self.unblockButton.setGeometry(QtCore.QRect(480, 400, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.unblockButton.setFont(font)
        self.unblockButton.setStyleSheet("border-style: outset;\n"
"border-width: 4px;\n"
"border-radius:15px;\n"
"border-color: beige;\n"
"padding: 9px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.unblockButton.setObjectName("unblockButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.blockButton.setText(_translate("MainWindow", "BLOCK"))
        self.label.setText(_translate("MainWindow", "             .WEBSITE BLOCKER."))
        self.backforwb.setText(_translate("MainWindow", "back"))
        self.unblockButton.setText(_translate("MainWindow", "UNBLOCK"))
import Resource


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
